apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: mohrizkimaulana/app-go:{{ .Values.env.APP_VERSION }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
