apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: pintu.doraemon.local
    http:
      paths:
      - pathType: Prefix
        path: "/go"
        backend:
          service:
            name: go-backend-service
            port: 
              number: 80
